server.port=8083
spring.application.name=ride-service

spring.datasource.url=jdbc:h2:mem:ridedb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

ridelink.jwt.secret=${RIDELINK_JWT_SECRET:RideLinkDemoSecretKeyForJwtSigningMustBeLongEnough123}
ridelink.driver-service-url=http://localhost:8082
ridelink.fare-service-url=http://localhost:8084

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
